---
- name: Get current deployment end time
  local_action: shell date +'%m/%d/%Y %r %z %Z'
  register: current_deployment_time
  become: no
  run_once: true

- name: Set last run time in motd
  replace:
    dest: "/etc/motd"
    regexp: "^(State:[ ]+).*$"
    replace: "\\1Last run at {{ current_deployment_time.stdout }}"
