---
- name: Send out ansible deployment ended broadcast message
  ansible.builtin.shell:
    warn: false
    cmd: |
      echo '+---------------------------------+
      | => ANSIBLE DEPLOYMENT ENDED! <= |
      +---------------------------------+' | wall
