---
- name: Send out ansible deployment ended broadcast message
  shell: |
    echo '+-------------------------------------------+
    | =>          DEPLOYMENT ENDED!          <= |
    +-------------------------------------------+' | wall
